=== iqb-specifications/unit-items/unit-items.schema.json
{
  "$id": "unit-items@0.1",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Unit Items.",
  "description": "Specification for items as part of the unit data.",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "uuid": {
        "description": "Hidden unique Id to find items better in big pools; generated automatically",
        "type": "string",
        "minLength": 1,
        "examples": [
          "d19188fc-02e3-439e-9ff9-4f8280f9f01c"
        ]
      },
      "id": {
        "description": "Visual Id, input by user",
        "type": "string",
        "minLength": 1,
        "examples": [
          "Drr4"
        ]
      },
      "description": {
        "type": "string"
      },
      "order": {
        "type": "integer",
        "default": 0
      },
      "sourceVariableId": {
        "description": "Id of variable providing value, code and/or score for the item",
        "type": "string",
        "minLength": 1
      },
      "sourceVariableUuid": {
        "description": "Hidden unique Id of variable providing value, code and/or score for the item",
        "type": "string",
        "minLength": 1
      },
      "visualAnchorVariableId": {
        "description": "Id of variable used to jump/scroll to the item to show/review",
        "type": "string",
        "minLength": 1
      },
      "visualAnchorVariableUuid": {
        "description": "Hidden unique Id of variable jump/scroll to the item to show/review",
        "type": "string",
        "minLength": 1
      },
      "createdAt": {
        "description": "Timestamp of creation",
        "type": "string",
        "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?Z$",
        "examples": [
          "2026-04-09T13:15:10.977Z"
        ]
      },
      "changedAt": {
        "description": "Timestamp of last change",
        "type": "string",
        "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?Z$",
        "examples": [
          "2026-04-09T13:15:10.977Z"
        ]
      },
      "metadata": {
        "type": "array",
        "items": {
          "$ref": "#/$defs/metadata"
        }
      }
    },
    "required": [
      "id"
    ],
    "allOf": [
      {
        "if": {
          "required": [
            "sourceVariableId"
          ]
        },
        "then": {
          "required": [
            "sourceVariableUuid"
          ]
        }
      },
      {
        "if": {
          "required": [
            "sourceVariableUuid"
          ]
        },
        "then": {
          "required": [
            "sourceVariableId"
          ]
        }
      },
      {
        "if": {
          "required": [
            "visualAnchorVariableId"
          ]
        },
        "then": {
          "required": [
            "visualAnchorVariableUuid"
          ]
        }
      },
      {
        "if": {
          "required": [
            "visualAnchorVariableUuid"
          ]
        },
        "then": {
          "required": [
            "visualAnchorVariableId"
          ]
        }
      }
    ],
    "additionalProperties": false
  },
  "$defs": {
    "metadata": {
      "$ref": "https://w3id.org/iqb/spec/metadata-values/3.0"
    }
  }
}

=== iqb-specifications/unit-items/test/unit-items1.json
[
    {
        "uuid": "d19188fc-02e3-439e-9ff9-4f8280f9f01c",
        "id": "Drr4",
        "order": 0,
        "createdAt": "2026-04-09T13:15:10.977Z",
        "changedAt": "2026-04-09T13:15:10.977Z"
    },
    {
        "uuid": "1a1a4296-dc38-4f2a-8ceb-e0c2067482ee",
        "id": "Uz788",
        "order": 0,
        "sourceVariableId": "radio_1",
        "sourceVariableUuid": "radio_1741871545529_1",
        "description": "Single-choice item result",
        "createdAt": "2026-04-09T13:15:10.977Z",
        "changedAt": "2026-04-09T13:15:10.977Z",
        "metadata": []
    }
]

=== iqb-specifications/unit-items/test/unit-items2.json
[
    {
        "uuid": "2f8fd99b-b171-4284-adc1-bf9ef03fbe18",
        "id": "Anchor-1",
        "order": 1,
        "description": "Item with dedicated anchor and source variables",
        "sourceVariableId": "text_1",
        "sourceVariableUuid": "text_1741871545529_1",
        "visualAnchorVariableId": "page_anchor_1",
        "visualAnchorVariableUuid": "page_anchor_1741871545529_1",
        "createdAt": "2026-04-09T13:15:10.977Z",
        "changedAt": "2026-04-09T13:15:10.977Z",
        "metadata": []
    }
]
